const SET_MENU = 'SET_MENU'
const SET_FOCUS_AREA = "SET_FOCUS_AREA"
const SET_CURRENT_GENRE = "SET_CURRENT_GENRE"
const SET_CURRENT_CONTENT_ID = "SET_CURRENT_CONTENT_ID"

export const ACTIONS = {
  SET_FOCUS_AREA,
  SET_MENU,
  SET_CURRENT_GENRE,
  SET_CURRENT_CONTENT_ID
}


